{{- range $group := .Values.participantGroups }}
{{- range $member := $group.members }}
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ $member }}-aks-helm-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ $member }}-aks-crossplane
      namespace: crossplane-system
      key: kubeconfig
{{- end }}  
{{- end }} 