{{- range $group := .Values.participantGroups }}
{{- range $member := $group.members }}
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ $member }}-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: ingress-nginx
  providerConfigRef:
    name: {{ $member }}-aks-helm-provider
{{- end }}  
{{- end }} 